add cicd

diff --git a/.github/workflows/dev.yaml b/.github/workflows/dev.yaml
--- a/.github/workflows/dev.yaml
+++ b/.github/workflows/dev.yaml
@@ -54,9 +54,12 @@ jobs:
             export COMMIT_HASH="${{ env.COMMIT_HASH }}"
             export COMMIT_DATE="${{ env.COMMIT_DATE }}"
             export AUTHOR_NAME="${{ env.AUTHOR_NAME }}"
-            echo "AUTHOR_NAME: $AUTHOR_NAME"
-            echo "COMMIT_HASH: $COMMIT_HASH"
-            echo "COMMIT_DATE: $COMMIT_DATE"
+            
+            # Проверьте, что переменные не пустые
+            if [ -z "$COMMIT_HASH" ] || [ -z "$COMMIT_DATE" ] || [ -z "$AUTHOR_NAME" ]; then
+              echo "Error: One or more environment variables are empty."
+              exit 1
+            fi
 
             docker stack deploy --with-registry-auth -c swarm/app/compose.yaml mithratrades-dev
           debug: true
